# -*- coding: utf-8 -*-
"""kaggle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcyn6iPb1gc4CVbCg4d3nugYxqpW2M0w
"""

import os
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam

sns.set_theme(style='whitegrid', font='serif')

def create_sequences(data, time_step=1):
    X, y = [], []
    for i in range(len(data) - time_step - 10):
        X.append(data[i:(i + time_step), 0])
        y.append(data[i + time_step + 9, 0])
    return np.array(X), np.array(y)

data = pd.read_csv('apple_stock.csv')

data.head()